### ISSUE TITLE
Why does SIP I/O need the JVM, it *seems* to be a Javascript/NodeJS project?

### ISSUE THREAD

**Issue by chrisdew** [fonoster/sipio#11]
I've not read every page of the wiki, but...

Why does SIP I/O need the JVM, it *seems* to be a Javascript/NodeJS project?

**Comment by psanders** [comment]
**Sip I/O** runs on Nashorn Engine. We use some common JS tooling(like *nmp*, *webpack*, etc) but it is Java at the core.
