### ISSUE TITLE
Load users from database

### ISSUE THREAD

**Issue by laowangnj** [fonoster/sipio#15]

**Comment by psanders** [comment]
We can create a plugin for this. Which databases would like to see support for?

**Comment by laowangnj** [comment]
Redis?

**Comment by psanders** [comment]
Hey @laowangnj 

We re-wrote the data api to allow for easy implementation of new data providers. Two new data providers were added, `redis_data_provider` and `restful_data_provider` and will be available in the next milestone. 

Please head to https://github.com/fonoster/sipio/wiki/General-Configuration for more information on how to configure an use the new data providers.
